### DISCUSSION TITLE
Syslog support

### DISCUSSION THREAD

**Discussion by draconx** [certbot/certbot#10760] [Feature Requests, Ideas]
(I hope this is the right place for letsencrypt feature requests)

Lets encrypt should (optionally) support logging via the system logger (syslog), instead of trying to manage its own log files.  The system logger can naturally do a better job of handling log files, because it is designed exclusively for that purpose.

**Comment by xrchz** [comment]
:+1: I think this is the only thing stopping me from running the client as non-root.

**Comment by dreaming-augustin** [comment]
The 2.0.0 milestone appears to be obsolete. Is there any plan to improve the logging facility of certbot?

**Comment by stale** [comment]
We've made a lot of changes to Certbot since this issue was opened. If you still have this issue with an up-to-date version of Certbot, can you please add a comment letting us know? This helps us to better see what issues are still affecting our users. If there is no further activity, this issue will be automatically closed.

**Comment by draconx** [comment]
It does not appear that syslog support has magically appeared in the latest version...

**Comment by astik** [comment]
Having certbot log in syslog would make it easier to add it to elasticsearch through filebeat, no specific configuration to do =P

**Comment by Nebucatnetzer** [comment]
@astik do you maybe have a good resource on how to get started with certbot and filebeat?
We would really to integrate certbot into our logging server but the debug logs are quite a mess.

**Comment by astik** [comment]
Unfortunately i have no idea about how to do so ... my logging system are missing certbot logs ='(

**Comment by Nebucatnetzer** [comment]
Too bad, but thank you anyway.

**Comment by daviessm** [comment]
+1 for this, logging to journald would also be nice to have.

**Comment by mikhailnov** [comment]
+1, useful for read-only containers.

**Comment by djlambert** [comment]
+1 for all the cases mentioned above

**Comment by NINNiT** [comment]
+1, would be really nice to have!

Edit: On some certbot installations (those using `snap`), certbot is using `systemd-timers`. 
It is thus possible to get log messages into `journald`. You can test this with `sudo journalctl -u snap.certbot.renew.service`

**Comment by Nebucatnetzer** [comment]
The following is a filebeat configuration you can use together with a Graylog sidecar.
If you just use filebeat alone I'm sure you can extract the relevant parts.

```
# Needed for Graylog {
fields_under_root: true
fields.collector_node_id: ${sidecar.nodeName}
fields.gl2_source_collector: ${sidecar.nodeId}
# }

filebeat.inputs:
- type: filestream
  id: co-srv-iproxy2-certbot
  paths:
    - /var/log/letsencrypt/*.log
  prospector.scanner.exclude_files: ['\.gz$']
  parsers:
    - multiline:
        type: pattern
        pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
        negate: true
        match: after
  
output.logstash:
   hosts: ["192.168.1.99:5044"]
path:
  data: /var/lib/graylog-sidecar/collectors/filebeat/data
  logs: /var/lib/graylog-sidecar/collectors/filebeat/log
```
