### ISSUE TITLE
Make Dockerfiles for each DNS plugin

### ISSUE THREAD

**Issue by zh99998** [certbot/certbot#5026]
## My operating system is (include version):
Debian 9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Docker

## I ran this command and it produced this output:
```yaml
version: '3'
services:
  certbot:
    image: certbot/certbot
    command: certonly --agree-tos --manual-public-ip-logging-ok --non-interactive -m zh99998@gmail.com --expand --dns-cloudxns --dns-cloudxns-credentials credentials.ini --test-cert -d xxxx
  ...
```
```
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --dns-cloudxns-credentials credentials.ini

```

## Certbot's behavior differed from what I expected because:
as https://certbot.eff.org/docs/using.html#certbot-command-line-options seems cloudxns is officially supported in certbot, but I can't find how to enable / install such plugin.
