### ISSUE TITLE
The certbot container keeps restarting

### ISSUE THREAD

**Issue by thomasmoors** [certbot/certbot#6309]
## My operating system is (include version):
Host: Windows 10 x64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
docker-compose file

```yaml
version: "3.7"

services:
  certbot:
    restart: unless-stopped
    image: certbot/certbot
    container_name: certbot_mp
```

## I ran this command and it produced this output:

`docker exec -it certbot_mp certbot certonly`

> Error response from daemon: Container afc675dfdd4371a37a0055ba2bdc3329dbd863661f05706252be8c3516742de3 is restarting, wait until the container is running

Portainers log says:

> Saving debug log to /var/log/letsencrypt/letsencrypt.log,
Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.

## Certbot's behavior differed from what I expected because:
I cannot run the desired command to obtain certificates
