### ISSUE TITLE
Speed up Azure Pipelines when doing a release

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8139]
When we create a release, we trigger a CI build for each of these events:

* A build for the tag
* A build for the a.b.x branch
* A build for the PR to update certbot-auto

In Travis, all jobs in a build would run to completion before any jobs in a subsequent build are started.

This is not the case in Azure Pipelines. There we make heavy use of stages allowing some parts of the build to wait on others to complete. For example, we wait on snaps to be built to test them. It appears that jobs that are initially blocked on another job have a lower queue priority than jobs triggered by a completely different build. As a result, the sequence of tests in runs in Azure is:

1. The majority of the tests on the tag run.
2. The majority of the test on the a.b.x branch run.
3. The tests on the PR run.
4. The initially blocked builds from the tag ruin.
5. The initially blocked builds from the PR run.

As a result of this, waiting for the builds on the tag to finish so you can finish the release process takes much longer. The Travis builds we had in the past for a release took ~30 mins. The Azure release took over more than 2.5 times as long. See https://dev.azure.com/certbot/certbot/_build/results?buildId=2283&view=results.

The best ideas I currently have to solve this doing one of:

1. Don't create the `*.x` branch until it is necessary to do a point release. If we go this route, I think we should document how to create this branch probably with an automated script to simplify the process.
2. (Doesn't work ☹️ )Make the tests for the tag and the `*.x` run in the same Azure Pipeline and set `batch=True`. See https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#batching-ci-runs.

EDIT: I largely rewrote this to provide more context.

**Comment by adferrand** [comment]
Aside the solution to find here, it would like to note that the overal time of this specific build is not normal. As one can see on this run for instance https://dev.azure.com/certbot/certbot/_build/results?buildId=2285 that the `TestAndPackage` step takes around 35 min usually, while on the run https://dev.azure.com/certbot/certbot/_build/results?buildId=2283 it took 1h10.

**Comment by bmw** [comment]
Sure, although I would like to note that I think we should expect it to be a normal occurrence every time we do a release because of all of the builds that get triggered that I described in my initial post.

**Comment by adferrand** [comment]
Of course, and we can expect more if we add the dns plugin snaps.

For the propositions, I like 2 because it would smartly use the fact that tags and branches can actually refer to the same commit.

**Comment by bmw** [comment]
> For the propositions, I like 2 because it would smartly use the fact that tags and branches can actually refer to the same commit.

Would it not even run a build for the `1.6.x` branch then if the tag started first?

For what it's worth, before writing this issue, I started playing with this approach and even went so far to combine all of our slight variations of the full test suite into one pipeline. An untested and quickly written version of that is:
```
# Advanced pipeline running our full test suite and deploying artifacts when appropriate.
trigger:
  branches:
    include:
      - '*.x'
      # When changing these triggers, please ensure the documentation under
      # "Running tests in CI" is still correct.
      - test-*
  tags:
    include:
      - v*
pr: none
schedules:
  - cron: "30 4 * * *"
    displayName: Nightly build
    branches:
      include:
      - master
    always: true

stages:
  - template: templates/stages/test-and-package-stage.yml
  - template: templates/stages/changelog-stage.yml
  - ${{ if not(or(startsWith(variables['Build.SourceBranchName'], 'test-'), endsWith(variables['Build.SourceBranchName'], '.x'))) }}:
    - template: templates/stages/deploy-stage.yml
  # Don't send Mattermost messages about failures on test- branches.
  - ${{ if not(startsWith(variables['Build.SourceBranchName'], 'test-')) }}:
    - template: templates/stages/notify-failure-stage.yml

```
