### ISSUE TITLE
Document and announce DNS plugin snaps

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#8142]
~~This is blocked on us having builds of our DNS plugin snaps available which is being tracked at https://github.com/certbot/certbot/issues/8041.~~

One thing to note though is it appears the DNS plugins will automatically try to connect to Certbot when they are installed so I think we should run `sudo snap set certbot trust-plugin-with-root=ok` before installing the DNS plugin and then the `sudo snap connect` command shouldn't be needed.

I also think we should:

- [x] Add documentation to certbot.eff.org which is being tracked at https://github.com/certbot/website/issues/603.
- [x] Briefly mention the availability of DNS plugin snaps in our docs in this repo under `certbot/docs`.
- [ ] Make an announcement about DNS plugin snaps on the community forum.

**Comment by ohemorange** [comment]
> One thing to note though is it appears the DNS plugins will automatically try to connect to Certbot when they are installed so I think we should run sudo snap set certbot trust-plugin-with-root=ok before installing the DNS plugin and then the sudo snap connect command shouldn't be needed.

This should only be true for snaps published on the snap store because it's based on the publisher, right? It certainly doesn't do this for snaps I compiled myself.

**Comment by bmw** [comment]
Yeah that's what I think is going on. I have the same behavior as you with snaps built locally.

**Comment by ohemorange** [comment]
> One thing to note though is it appears the DNS plugins will automatically try to connect to Certbot when they are installed so I think we should run sudo snap set certbot trust-plugin-with-root=ok before installing the DNS plugin and then the sudo snap connect command shouldn't be needed.

We should also make sure to document this in case something happens and it's installed before they're run

**Comment by ohemorange** [comment]
> We should also make sure to document this in case something happens and it's installed before they're run

Actually, thinking about this more, I'd rather have people set the variable then install the plugin again instead of manually specifying connections. That seems like the sort of thing people shouldn't have to do. We may want a separate guide for people building third-party dns plugin snaps to write their own instructions, which will be different, though. Probably in `certbot/docs`.

**Comment by ohemorange** [comment]
Proposed announcement text is here; comments welcome: https://docs.google.com/document/d/16fMLTCAnPVaTrf6BFa0TYF55k3kSX2Axh3dtpdhx53A/edit?usp=sharing

**Comment by a14m** [comment]
Thanks a lot @bmw, I can confirm that the following commands work (for installing the plugin from snap)

```
sudo snap install --classic certbot
sudo snap set certbot trust-plugin-with-root=ok
sudo snap install --channel latest/beta certbot-dns-route53
```

also via ansible
```
- name: "Install: certbot (letsencrypt)"
  become: yes
  snap:
    name: certbot
    classic: yes

- name: "Trust certbot plugin install"
  become: yes
  shell: "snap set certbot trust-plugin-with-root=ok"
  changed_when: false

- name: "Install: certbot_dns_route53"
  become: yes
  snap:
    name: certbot-dns-route53
    channel: latest/beta
```
