### ISSUE TITLE
Docker dns-cloudflare image fails to recognize the --dns-cloudflare-credentials parameters 

### ISSUE THREAD

**Issue by dnwk** [certbot/certbot#9484]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 22.04

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

Docker image: certbot/dns-cloudflare

## I ran this command and it produced this output:
This is in the docker compose yml

docker-compose.override.yml

```
version: "3.2"

services:
    certbot:
        image: certbot/dns-cloudflare:latest
        volumes:
        - ./certs/:/etc/letsencrypt
        - /opt/cloudflare:/opt/authentik-dockerized/cloudflare
        command:
            - certonly
            - --non-interactive
            - --dns-cloudflare
            - --dns-cloudflare-credentials /opt/cloudflare/credentials
            - --agree-tos
            - -m email
            - -d domain
```

## Certbot's behavior differed from what I expected because:
It generated this error
certbot: error: unrecognized arguments: --dns-cloudflare-credentials /opt/cloudflare/credentials

###### Logs are str/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

certbot: error: unrecognized arguments: --dns-cloudflare-credentials /opt/cloudflare/credentials
